### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by wenboLee** [future-challenger/petshop#13]
E:\node\express\petshop-master\server\server.js:5
import 'babel-polyfill'
^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by future-challenger** [comment]
如果你用的是VSCode的话，把下面的配置贴在launch.json文件里：
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "node",
            "protocol": "inspector",
            "request": "launch",
            "program": "${workspaceRoot}/server/app.js",
            "stopOnEntry": true,
            "args": [],
            "cwd": "${workspaceRoot}",
            "preLaunchTask": null,
            "runtimeExecutable": null, //"${workspaceRoot}/node_modules/.bin/babel-node"
            "runtimeArgs": [
                "--nolazy"
                // ,"--debug"
                ,"--require",
                "babel-register"
            ],
            "env": {
                "NODE_ENV": "development"
            },
            "console": "integratedTerminal",
            "sourceMaps": true,
            "outFiles": ["${workspaceRoot}/built/server/**/*.js"]
        },
        {
            "name": "Attach",
            "type": "node",
            "request": "attach",
            "port": 5858,
            "address": "localhost",
            "restart": false,
            "sourceMaps": false,
            "outFiles": [],
            "localRoot": "${workspaceRoot}",
            "remoteRoot": null
        }
    ]
}
```
出这个问题的原因在于，petshop的代码使用ES2015的语法写的。所以，你需要用babel转码后在运行才可以
